import asyncio
from typing import Callable

from py_astealth.generated.async_interface import AsyncInterface
from py_astealth.stealth_api import StealthApi
from py_astealth.stealth_client import AsyncStealthClient
from py_astealth.core.api_specification import MethodSpec, implement_api
from py_astealth.stealth_session import StealthSession


def create_async_method(method_spec: MethodSpec) -> Callable:
    """
    async method implementation
    """
    async def api_method_impl(self: AsyncStealthClient, *args, **kwargs):
        # 'self' is an instance of AsyncStealthApiClient, which inherits from AsyncStealthClient.
        # It just passes the call down to 'call_method'.
        return await self.call_method(method_spec, *args)

    # for better debugging
    api_method_impl.__name__ = method_spec.name
    api_method_impl.__doc__ = f"Async API method for {method_spec.name}(...)"
    return api_method_impl


@implement_api(StealthApi, method_factory=create_async_method)
class AsyncStealthApiClient(AsyncInterface, AsyncStealthClient):
    """
    Stealth asynchronous client. All API methods from StealthApi are generated by a decorator,
    using the create_async_proxy_method factory
    """
    def __init__(self, session: StealthSession = None):
        super().__init__(session)

    async def __aenter__(self):
        await self.connect()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        self.close()

    async def get_event(self):
        """
        return the next event from the queue or None if there are no events
        """
        try:
            return self.events.get_nowait()
        except asyncio.QueueEmpty:
            return None


