VERSION = 2, 8, 0, 0

DEFAULT_STEALTH_HOST = '127.0.0.1'
DEFAULT_STEALTH_PORT = 47602

SOCK_TIMEOUT = 10.0
GET_PORT_ATTEMPT_COUNT = 3

USE_STEALTH_SYSTEM_JOURNAL = True
ERROR_FILTER = True
REMOVE_NEW_LINES = True
